version: '3.8'

services:
  redis:
    image: docker.io/redis:7-alpine
    container_name: transaction-redis
    ports:
      - "6379:6379"
    networks:
      - transaction-network

  backend:
    image: transaction-management/backend:latest
    container_name: transaction-backend
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - transaction-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    image: transaction-management/frontend:latest
    container_name: transaction-frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - transaction-network

networks:
  transaction-network:
    driver: bridge